In [ ]:
print("hello world")

hello world

In [ ]:
import matplotlib

In [2]:
import pandas as pd

df = pd.read_csv(
    r"C:\Users\samue\Scripts\Nofis-Classifier\data\raw\202501_NFe\202501_NFe_NotaFiscalItem.csv",
    sep=";",
    encoding="cp1252",
    decimal=",",
)

df.head()

,CHAVE DE ACESSO,MODELO,SÉRIE,NÚMERO,NATUREZA DA OPERAÇÃO,DATA EMISSÃO,CPF/CNPJ Emitente,RAZÃO SOCIAL EMITENTE,INSCRIÇÃO ESTADUAL EMITENTE,UF EMITENTE,...,PRESENÇA DO COMPRADOR,NÚMERO PRODUTO,DESCRIÇÃO DO PRODUTO/SERVIÇO,CÓDIGO NCM/SH,NCM/SH (TIPO DE PRODUTO),CFOP,QUANTIDADE,UNIDADE,VALOR UNITÁRIO,VALOR TOTAL
0,32250148658655000188550010000007301109131230,55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...,1,730,VENDA MERC DENTRO ESTADO,01/01/2025 00:00:00,48658655000188,FADINI SOLUCOES LTDA,83998284,ES,...,1 - OPERAÇÃO PRESENCIAL,1,FREEZER VERTICAL 1 PORTA 220V,84184000,Congeladores (freezers) verticais tipo armário...,5102,1.00,UNIDAD,2970.00,2970.00
1,51250104695497000160550110000434184166743940,55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...,11,43418,VENDA DE COMBUSTIVEL OU LUBRIFICANTE ADQUIRIDO...,01/01/2025 06:19:19,04695497000160,C. MITIKO SACUNO LTDA,132046059,MT,...,1 - OPERAÇÃO PRESENCIAL,1,DS DIESEL S10 COMUM,27101921,Gasóleo (óleo diesel),5656,66.92,LITRO,6.89,461.07
2,51250104695497000160550110000434191056340194,55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...,11,43419,VENDA DE COMBUSTIVEL OU LUBRIFICANTE ADQUIRIDO...,01/01/2025 06:26:54,04695497000160,C. MITIKO SACUNO LTDA,132046059,MT,...,1 - OPERAÇÃO PRESENCIAL,1,GC GASOLINA COMUM,27101259,"Outras gasolinas, exceto para aviação",5656,102.17,LITRO,6.68,682.49
3,33250128503456000193550020000440181101927108,55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...,2,44018,VENDA,01/01/2025 06:41:12,28503456000193,POSTO DOS PESCADORES LTDA,80607644,RJ,...,1 - OPERAÇÃO PRESENCIAL,1,GASOLINA COMUM,27101259,"Outras gasolinas, exceto para aviação",5656,54.11,L,7.19,389.05
4,33250129051570000192550060000573941110143139,55 - NF-E EMITIDA EM SUBSTITUIÇÃO AO MODELO 1 ...,6,57394,VENDA,01/01/2025 06:43:55,29051570000192,POSTO DOS SANTOS REIS LTDA,80610599,RJ,...,1 - OPERAÇÃO PRESENCIAL,1,DIESEL S10,27101921,Gasóleo (óleo diesel),5656,73.30,L,5.71,418.54

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 369683 entries, 0 to 369682
Data columns (total 31 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   CHAVE DE ACESSO                     369683 non-null  object
 1   MODELO                              369683 non-null  str
 2   SÉRIE                               369683 non-null  int64
 3   NÚMERO                              369683 non-null  int64
 4   NATUREZA DA OPERAÇÃO                369683 non-null  str
 5   DATA EMISSÃO                        369683 non-null  str
 6   CPF/CNPJ Emitente                   369683 non-null  str
 7   RAZÃO SOCIAL EMITENTE               369683 non-null  str
 8   INSCRIÇÃO ESTADUAL EMITENTE         369683 non-null  int64
 9   UF EMITENTE                         369683 non-null  str
 10  MUNICÍPIO EMITENTE                  369683 non-null  str
 11  CÓDIGO ÓRGÃO SUPERIOR DESTINATÁRIO  369683 non-null  int64
 12  ÓRGÃO SUPERIOR DESTINATÁRIO         369683 non-null  str
 13  CÓDIGO ÓRGÃO DESTINATÁRIO           369683 non-null  int64
 14  ÓRGÃO DESTINATÁRIO                  369683 non-null  str
 15  CNPJ DESTINATÁRIO                   369683 non-null  int64
 16  NOME DESTINATÁRIO                   369683 non-null  str
 17  UF DESTINATÁRIO                     369683 non-null  str
 18  INDICADOR IE DESTINATÁRIO           369683 non-null  str
 19  DESTINO DA OPERAÇÃO                 369683 non-null  str
 20  CONSUMIDOR FINAL                    369683 non-null  str
 21  PRESENÇA DO COMPRADOR               369683 non-null  str
 22  NÚMERO PRODUTO                      369683 non-null  int64
 23  DESCRIÇÃO DO PRODUTO/SERVIÇO        369683 non-null  str
 24  CÓDIGO NCM/SH                       369683 non-null  int64
 25  NCM/SH (TIPO DE PRODUTO)            347601 non-null  str
 26  CFOP                                369683 non-null  int64
 27  QUANTIDADE                          369683 non-null  float64
 28  UNIDADE                             369304 non-null  str
 29  VALOR UNITÁRIO                      369683 non-null  float64
 30  VALOR TOTAL                         369683 non-null  float64
dtypes: float64(3), int64(9), object(1), str(18)
memory usage: 87.4+ MB

In [4]:
df.columns

Index(['CHAVE DE ACESSO', 'MODELO', 'SÉRIE', 'NÚMERO', 'NATUREZA DA OPERAÇÃO',
       'DATA EMISSÃO', 'CPF/CNPJ Emitente', 'RAZÃO SOCIAL EMITENTE',
       'INSCRIÇÃO ESTADUAL EMITENTE', 'UF EMITENTE', 'MUNICÍPIO EMITENTE',
       'CÓDIGO ÓRGÃO SUPERIOR DESTINATÁRIO', 'ÓRGÃO SUPERIOR DESTINATÁRIO',
       'CÓDIGO ÓRGÃO DESTINATÁRIO', 'ÓRGÃO DESTINATÁRIO', 'CNPJ DESTINATÁRIO',
       'NOME DESTINATÁRIO', 'UF DESTINATÁRIO', 'INDICADOR IE DESTINATÁRIO',
       'DESTINO DA OPERAÇÃO', 'CONSUMIDOR FINAL', 'PRESENÇA DO COMPRADOR',
       'NÚMERO PRODUTO', 'DESCRIÇÃO DO PRODUTO/SERVIÇO', 'CÓDIGO NCM/SH',
       'NCM/SH (TIPO DE PRODUTO)', 'CFOP', 'QUANTIDADE', 'UNIDADE',
       'VALOR UNITÁRIO', 'VALOR TOTAL'],
      dtype='str')

In [7]:
df_selected = df[['DESCRIÇÃO DO PRODUTO/SERVIÇO', 'QUANTIDADE', 'CÓDIGO NCM/SH', 'VALOR UNITÁRIO']]

df_selected.head()

    DESCRIÇÃO DO PRODUTO/SERVIÇO  QUANTIDADE  CÓDIGO NCM/SH  VALOR UNITÁRIO
0  FREEZER VERTICAL 1 PORTA 220V        1.00       84184000         2970.00
1            DS DIESEL S10 COMUM       66.92       27101921            6.89
2              GC GASOLINA COMUM      102.17       27101259            6.68
3                 GASOLINA COMUM       54.11       27101259            7.19
4                     DIESEL S10       73.30       27101921            5.71

In [15]:
df_selected['DESCRIÇÃO DO PRODUTO/SERVIÇO'].value_counts()

DESCRIÇÃO DO PRODUTO/SERVIÇO
PERSONALIZACAO NOVO PASSAPORTE BRASILEIRO PACOM DPF 32 PAG.    4534
CENOURA                                                        1027
MELANCIA                                                        918
GASOLINA COMUM                                                  902
CEBOLA                                                          769
                                                               ...
CEFEPIMA 2 GR CX/50 F/A (G) (.)                                   1
CIPROFLOXACINA 500MG C/300 CPR (G) (PRATI)                        1
MÃO DE OBRA/ DIAGNÓSTICO POR SCANNER                              1
PILHA, TAMANHO PALITO, TIPO COMUM, MODELO AAA                     1
Leite Cru Refrigerado                                             1
Name: count, Length: 151290, dtype: int64